export { default as DaySun } from './Day sun.svg';
export { default as DayClouds } from './Day Clouds.svg';
export { default as DayWind } from './Day Wind.svg';
export { default as DayRain } from './Day Rain.svg';
export { default as DaySnow } from './Day Snow.svg';
export { default as DayStorm } from './Day Storm.svg';
export { default as NightMoon } from './Night Moon.svg';
export { default as NightClouds } from './Night Clouds.svg';
export { default as NightWind } from './Night Wind.svg';
export { default as NightRain } from './Night Rain.svg';
export { default as NightSnow } from './Night Snow.svg';
export { default as NightStorm } from './Night Storm.svg';
export { default as plus } from './plus.svg';
export { default as map_pin } from './map-pin.svg';
export { default as pin_clay } from './pin-clay.svg';
export { default as pin_color } from './pin-color.svg';
export { default as search } from './search.svg';
export { default as close } from './close.svg';
export { default as check } from './check.svg';
export { default as scissors } from './scissor.svg';
export { default as trash_can } from './trash-can.svg';
export { default as next } from './next.svg';
export { default as logout } from './logout.svg';
